# Generated by Django 2.2.12 on 2020-07-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_foto_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='foto_receita',
        ),
    ]
